### ISSUE TITLE
docker部署samwaf时，用户访问无法记录真实IP

### ISSUE THREAD

**Issue by ShiDai567** [samwafgo/samwaf.github.io#5]
![Image](https://github.com/user-attachments/assets/65887b29-3253-46d9-8510-097ae1f2a6fc)

![Image](https://github.com/user-attachments/assets/d44b8ef6-daa0-43fe-b70c-89602c80a6ed)
docker配置文件如下
```yml
networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "nginx_net"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
services:
  samwaf:
    image: samwaf/samwaf
    container_name: samwaf
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - 8082:80 # Public HTTP Port
      - 8445:443 # Public HTTPS Port
      - 84:26666  # Admin Web Port
    volumes:
      - ${CONFIG_DIR}/samwaf/conf:/app/conf
      - ${CONFIG_DIR}/samwaf/data:/app/data
      - ${CONFIG_DIR}/samwaf/logs:/app/logs
      - ${CONFIG_DIR}/samwaf/ssl:/app/ssl
    networks:
      net:
        ipv4_address: 172.18.0.6
```
